name: qcodestest2
channels: 
 - defaults
 - conda-forge
dependencies:
 - h5py
 - matplotlib=2.2.2
 - pyqtgraph 
 - python=3.6
 - jsonschema
 - pyvisa=1.9.0
 - QtPy
 - sip
 - pyqt=5.9.2
 - numpy=1.13.3
 - jupyter=1.0.0
 - hypothesis
 - pytest
 - pytest-runner
 - spyder
 - pyzmq
