name: qcodes
channels: 
 - defaults
dependencies:
 - h5py
 - matplotlib=2.2.2
 - pyqtgraph 
 - python=3.6
 - jsonschema
 - QtPy
 - sip
 - pyqt=5.9.2
 - numpy=1.14.3
 - jupyter=1.0.0
 - hypothesis
 - pytest
 - pytest-runner
 - spyder
 - pyzmq
 - pyyaml
 - lxml
 - scipy
 - pip:
    - pyvisa
