name: Run mypy and pytest

on:
  push:
    branches:
      - 'master'
      - 'release/*'
    tags:
      - 'v*'
  pull_request:

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: [3.7, 3.8, 3.9]
    env:
      DISPLAY: ':99.0'
      OS: ${{ matrix.os }}
      PYTHON: ${{ matrix.python-version }}

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: '0'
    - name: setup ubuntu-latest xvfb
      uses: ./.github/actions/setup-ubuntu-latest-xvfb
    - name: install 3.9 build deps ubuntu
      run: sudo apt install libhdf5-dev libxml2-dev libxml2 libxslt1.1 libxslt1-dev
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: prepare pip cache
      id: prepare-cache-pip
      uses: ./.github/actions/prepare-cache-pip
    - name: pip cache
      uses: actions/cache@v2
      with:
        path: ${{ steps.prepare-cache-pip.outputs.cache-dir }}
        key: ${{ runner.os }}-${{ matrix.python-version }}-pip-${{ hashFiles('**/requirements.txt') }}-${{ hashFiles('**/test_requirements.txt') }}-${{ hashFiles('**/setup.py') }}
        restore-keys: |
          ${{ runner.os }}-${{ matrix.python-version }}-pip-
    - name: install requirements.txt
      run: |
        pip install -r requirements.txt --use-feature=2020-resolver
    - name: install test_requirements.txt
      run: |
        pip install -r test_requirements.txt --use-feature=2020-resolver
    - name: generate test dbs
      uses: ./.github/actions/generate-test-dbs
    - name: install qcodes
      run: pip install . --use-feature=2020-resolver
    - name: Run Mypy
      run: mypy qcodes
    - name: Run parallel tests
      run: |
        cd qcodes
        py.test -m "not serial" --cov=qcodes --cov-report xml --cov-config=.coveragerc --hypothesis-profile ci
    - name: Run serial tests
      run: |
        cd qcodes
        py.test -n 1 -m serial --cov-append --cov=qcodes --cov-report xml --cov-config=.coveragerc --hypothesis-profile ci
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
      with:
        file: ./qcodes/coverage.xml
        env_vars: OS,PYTHON
